In [ ]:
import pandas as pd
df1=pd.read_csv("/content/ENRNIE2.0_english_hope.csv")
df2=pd.read_csv("/content/RobERTA_english_hope.csv")
df3=pd.read_csv("/content/BERT_english_hope.csv")

In [ ]:
l1=df1['Labels']
l2=df2['Labels']
l3=df3['Labels']

In [ ]:
l1

0      Non_hope_speech
1      Non_hope_speech
2      Non_hope_speech
3      Non_hope_speech
4      Non_hope_speech
            ...
383    Non_hope_speech
384    Non_hope_speech
385    Non_hope_speech
386    Non_hope_speech
387    Non_hope_speech
Name: Labels, Length: 388, dtype: object

In [ ]:
df1

                                                  text           Labels
0                     Wow videos long They good points  Non_hope_speech
1    I know none business 75k income Is household c...  Non_hope_speech
2                                   Hope Is new Pokmon  Non_hope_speech
3    Almost every time someone depicts davidian sta...  Non_hope_speech
4                             disrespect body It YOURS  Non_hope_speech
..                                                 ...              ...
383         Great questions finally great answers well  Non_hope_speech
384                                           That man  Non_hope_speech
385  I wish people criticise would watch stop givin...  Non_hope_speech
386  I wanna hug MadonnannnI LOVE interviewso rawso...  Non_hope_speech
387                                     Shes charlatan  Non_hope_speech

[388 rows x 2 columns]

In [ ]:
l4=[]

In [ ]:
for i in range (len(l1)):
  c1=0
  c2=0
  if l1[i]=='Non_hope_speech':
    c1+=1 
  else:
    c2+=1
  if l2[i]=='Non_hope_speech':
    c1+=1 
  else:
    c2+=1
  if l3[i]=='Non_hope_speech':
    c1+=1 
  else:
    c2+=1
  if c1>=2:
    l4.append('Non_hope_speech')
  else c2>=2:
    l4.append("Hope_speech")

In [ ]:
test=pd.read_csv('/content/drive/MyDrive/ACL_sharedtask/Hope Speech/Hope_ENG_test.csv')
test.columns=['text']
test

                                                  text
0      Wow your videos are long. They have good points
1    I know this is none of my business but 75k+ in...
2                         Hope? Is that a new PokÃ©mon?
3    Almost every time someone depicts a davidian s...
4    how can you disrespect your own body? It is YO...
..                                                 ...
383  Great questions finally... great answers as we...
384                                     That is a man.
385  I wish people who criticise her would watch th...
386  I just wanna hug Madonna.nnnI LOVE how she is ...
387                                 She's a charlatan!

[388 rows x 1 columns]

In [ ]:
test['Lables']=l4

In [ ]:
test.to_csv('Final_English.csv')